steps:
# Deploy to Cloud Functions 2nd Gen
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['functions', 'deploy', 'store-tweet-scores', 
    '--gen2',
    '--trigger-http',
    '--runtime', 'python310',
    '--region', 'us-west1', 
    '--source', '.',
    '--entry-point', 'event_receiver']
